'use client';

import './globals.css';
import { Inter } from 'next/font/google';

import { store } from '@/app/store/store'; // import it here?

import { Provider } from 'react-redux'; // then use with this...
import { Elements } from '@stripe/react-stripe-js';
import { loadStripe } from '@stripe/stripe-js';

const stripePromise = loadStripe(
  'pk_live_51N30rHGF7NYNyMJjer7EYdAxf6nrZd5CxrLq5tzBNJWoJ4XjAq3na6xQ4pZE1p9PuYY9fvcwcZe1DVuNrdVECfqJ00GJtAz5pK'
);
const inter = Inter({ subsets: ['latin'] });
//
// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Elements stripe={stripePromise}>
      <Provider store={store}>
        <html lang='en'>
          <body className={inter.className}>{children}</body>
        </html>
      </Provider>
    </Elements>
  );
}
